version: "3.7"
services:
  mysql:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    ports:
      - "8080:8080"
    restart: always
    depends_on:
     - mysql
    environment:
     RDS_HOSTNAME: mysql
     RDS_PORT: 3306
     RDS_DB_NAME: todos
     RDS_USERNAME: todos-user
     RDS_PASSWORD: dummytodos

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - spring-boot-mysql-network
    ports:
      - "3306:3306"
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_DATABASE: todos
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos

networks:
  spring-boot-mysql-network:
    driver: bridge

volumes:
    db_data: {}
